import { Guia } from "../guia/guia";
import { Item } from "../item/item";
import { VentaCredito } from "../venta_credito/venta-credito";

export class EnviarNubefact {
    operacion: string;
    tipo_de_comprobante: number;
    serie: string;
    numero: number;
    sunat_transaction: number;
    cliente_tipo_de_documento: number;
    cliente_numero_de_documento: string;
    cliente_denominacion: string;
    cliente_direccion: string;
    cliente_email?: string ;
    cliente_email_1?: string ;
    cliente_email_2?: string ;
    fecha_de_emision: string;  // Utilizamos string para fechas en formato 'dd-MM-yyyy'
    fecha_de_vencimiento?: string ;
    moneda: number;
    tipo_de_cambio?: number ;
    porcentaje_de_igv: number;
    descuento_global?: number ;
    total_descuento?: number ;
    total_anticipo?: number ;
    total_gravada?: number ;
    total_inafecta?: number ;
    total_exonerada?: number ;
    total_igv?: number ;
    total_gratuita?: number ;
    total_otros_cargos?: number ;
    total: number;
    percepcion_tipo?: number ;
    percepcion_base_imponible?: number ;
    total_percepcion?: number ;
    total_incluido_percepcion?: number ;
    retencion_tipo?: number ;
    retencion_base_imponible?: number ;
    total_retencion?: number ;
    total_impuestos_bolsas?: number ;
    observaciones?: string;
    documento_que_se_modifica_tipo?: number ;
    documento_que_se_modifica_serie?: string;
    documento_que_se_modifica_numero?: number ;
    tipo_de_nota_de_credito?: number ;
    tipo_de_nota_de_debito?: number ;
    enviar_automaticamente_a_la_sunat?: boolean ;
    enviar_automaticamente_al_cliente?: boolean ;
    codigo_unico?: string;
    condiciones_de_pago?: string;
    medio_de_pago?: string;
    placa_vehiculo?: string;
    orden_compra_servicio?: string;
    detraccion?: boolean ;
    detraccion_tipo?: number ;
    detraccion_total?: number ;
    detraccion_porcentaje?: number ;
    medio_de_pago_detraccion?: number ;
    ubigeo_origen?: number ;
    direccion_origen?: string;
    ubigeo_destino?: number ;
    direccion_destino?: string;
    detalle_viaje?: string;
    val_ref_serv_trans?: number ;
    val_ref_carga_efec?: number ;
    val_ref_carga_util?: number ;
    punto_origen_viaje?: number ;
    punto_destino_viaje?: number ;
    descripcion_tramo?: string;
    val_ref_carga_efec_tramo_virtual?: number ;
    configuracion_vehicular?: string;
    carga_util_tonel_metricas?: number ;
    carga_efec_tonel_metricas?: number ;
    val_ref_tonel_metrica?: number ;
    val_pre_ref_carga_util_nominal?: number ;
    indicador_aplicacion_retorno_vacio?: boolean ;
    matricula_emb_pesquera?: string;
    nombre_emb_pesquera?: string;
    descripcion_tipo_especie_vendida?: string;
    lugar_de_descarga?: string;
    cantidad_especie_vendida?: number ;
    fecha_de_descarga?: string ;
    formato_de_pdf?: string;
    generado_por_contingencia?: boolean ;
    bienes_region_selva?: boolean ;
    servicios_region_selva?: boolean ;
    nubecont_tipo_de_venta_codigo?: string;
    items?: Item[];  // Asumiendo que Item es otra clase definida en tu proyecto
    guias?: Guia[];  // Asumiendo que Guia es otra clase definida en tu proyecto
    venta_al_credito?: VentaCredito[]; 
}
